# Generated by Django 4.1.3 on 2023-04-15 10:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courier', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourierCourierCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('courier_center_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courier.couriercenter', verbose_name='CourierCenter')),
                ('courier_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Courier')),
            ],
            options={
                'verbose_name': 'CourierCourierCenter',
                'verbose_name_plural': 'CourierCourierCenters',
            },
        ),
    ]
