# Generated by Django 4.1.3 on 2023-04-16 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0003_otp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OTP',
        ),
    ]
