# Generated by Django 4.1.3 on 2023-04-15 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('oblast', models.CharField(blank=True, max_length=255, null=True, verbose_name='Oblast')),
                ('city', models.CharField(blank=True, max_length=255, null=True, verbose_name='City')),
                ('street', models.CharField(blank=True, max_length=255, null=True, verbose_name='Street')),
                ('house_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='Apartment number')),
                ('apartment', models.CharField(blank=True, max_length=255, null=True, verbose_name='Apartment')),
                ('entrance', models.CharField(blank=True, max_length=255, null=True, verbose_name='Entrance')),
                ('floor', models.CharField(blank=True, max_length=255, null=True, verbose_name='Floor')),
                ('housing', models.CharField(blank=True, max_length=255, null=True, verbose_name='Housing')),
                ('residential_complex', models.CharField(blank=True, max_length=255, null=True, verbose_name='Residential complex')),
                ('additional_info', models.CharField(blank=True, max_length=255, null=True, verbose_name='Additional info')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
