# Generated by Django 4.1.3 on 2023-04-16 01:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0004_delete_otp'),
        ('orders', '0004_otp_is_verified_by_con'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='courier_center_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courier.couriercenter', verbose_name='Courier center'),
        ),
    ]
