# Generated by Django 4.1.3 on 2023-04-16 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_courier_center_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Price'),
        ),
    ]
