# Generated by Django 4.1.3 on 2023-04-16 00:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('con', '0002_con_created_at_con_is_active_con_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffCon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('con_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='con.con')),
                ('staff_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'StaffCon',
                'verbose_name_plural': 'StaffCons',
            },
        ),
    ]
